# wadoon/msml_tutorial_server
#


FROM wadoon/msml_tutorial_server:latest

MAINTAINER Alexander Weigl <Alexander.Weigl@student.kit.edu>

WORKDIR /root

ENTRYPOINT ["/usr/bin/ssh"]


# TODO add tutorial files
