# wadoon/msml_tutorial_local
FROM wadoon/msml_tutorial_base:2015.04.20

MAINTAINER Alexander Weigl <Alexander.Weigl@student.kit.edu>

WORKDIR /apps

ADD start /root/start

RUN chmod 755 /root/start

ENTRYPOINT ["/root/start"]

# TODO add tutorial files
