#!/bin/bash -x

# uid and gid of host user
USER_UID=${USER_UID:-1000}
USER_GID=${USER_GID:-1000}

# create user group
if ! getent group anonymous >/dev/null; then
	groupadd -f -g ${USER_GID} anonymous
fi

# create user with uid and gid matching that of the host user
if ! getent passwd anonymous >/dev/null; then
	adduser --uid ${USER_UID} --gid ${USER_GID} \
		--gecos 'Anonymous' anonymous
fi

extra_opts=

addgroup anonymous users 

#chown anonymous:anonymous -R /root

su anonymous
